/**
 * This file is auto-generated by `npm run generate:types`.
 * Run that command after changing any Collection or Global schema.
 * The types below are hand-authored stubs — they will be replaced on first generate.
 */

// ── Media ────────────────────────────────────────────────
export interface Media {
  id: string
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  url?: string | null
  alt: string
  caption?: string | null
  sizes?: {
    thumbnail?: { url?: string | null; width?: number | null; height?: number | null }
    card?:      { url?: string | null; width?: number | null; height?: number | null }
    hero?:      { url?: string | null; width?: number | null; height?: number | null }
  }
  createdAt: string
  updatedAt: string
}

// ── School ───────────────────────────────────────────────
export interface School {
  id: string
  name: string
  code?: string | null
  description?: string | null
  icon?: Media | string | null
  createdAt: string
  updatedAt: string
}

// ── Program ──────────────────────────────────────────────
export interface Program {
  id: string
  title: string
  slug: string
  level: 'UG' | 'PG' | 'PhD'
  school?: School | string | null
  durationYears?: number | null
  intakeCapacity?: number | null
  tuitionFeePerYear?: number | null
  specializations?: Array<{ id?: string; specialization: string }> | null
  eligibilityCriteria?: Record<string, unknown> | null // Lexical JSON
  published: boolean
  createdAt: string
  updatedAt: string
}

// ── Centre of Excellence ─────────────────────────────────
export interface CentreOfExcellence {
  id: string
  name: string
  industryPartner?: string | null
  description?: string | null
  image?: Media | string | null
  keyHighlights?: Array<{ id?: string; highlight: string }> | null
  gradientFrom?: string | null
  gradientTo?: string | null
  createdAt: string
  updatedAt: string
}

// ── Placement ────────────────────────────────────────────
export interface Placement {
  id: string
  year: number
  highestPackage?: string | null
  averagePackage?: string | null
  totalOffers?: number | null
  topRecruiters?: Array<{
    id?: string
    name: string
    logo?: Media | string | null
  }> | null
  alumniTestimonials?: Array<{
    id?: string
    name: string
    program?: string | null
    company?: string | null
    quote?: string | null
    photo?: Media | string | null
    initials?: string | null
    avatarColor?: string | null
  }> | null
  createdAt: string
  updatedAt: string
}

// ── Page (simplified) ────────────────────────────────────
export interface Page {
  id: string
  title: string
  slug: string
  meta?: {
    title?: string | null
    description?: string | null
  } | null
  layout?: Block[] | null
  published: boolean
  createdAt: string
  updatedAt: string
}

// ── Block types ──────────────────────────────────────────
export type Block =
  | HeroBlock
  | StatsBlock
  | ProgramExplorerBlock
  | CentresOfExcellenceBlock
  | PlacementTickerBlock
  | CallToActionBlock

export interface HeroBlock {
  blockType: 'hero'
  id?: string | null
  badge?: string | null
  headline: string
  subheadline?: string | null
  backgroundMedia?: Media | string | null
  primaryCta?: { label?: string | null; url?: string | null }
  secondaryCta?: { label?: string | null; url?: string | null }
  quickActions?: Array<{
    id?: string
    label: string
    url?: string | null
    icon?: string | null
  }> | null
}

export interface StatsBlock {
  blockType: 'stats'
  id?: string | null
  stats?: Array<{
    id?: string
    value: string
    label: string
    target?: number | null
    suffix?: string | null
  }> | null
}

export interface ProgramExplorerBlock {
  blockType: 'program-explorer'
  id?: string | null
  heading?: string | null
  subheading?: string | null
}

export interface CentresOfExcellenceBlock {
  blockType: 'centres-of-excellence'
  id?: string | null
  heading?: string | null
  subheading?: string | null
}

export interface PlacementTickerBlock {
  blockType: 'placement-ticker'
  id?: string | null
  heading?: string | null
  subheading?: string | null
}

export interface CallToActionBlock {
  blockType: 'call-to-action'
  id?: string | null
  heading?: string | null
  subheading?: string | null
  buttonLabel?: string | null
  buttonUrl?: string | null
  variant?: 'amber' | 'navy' | null
}

// ── Globals ──────────────────────────────────────────────
export interface HeaderGlobal {
  topBarText?: string | null
  helplineNumber?: string | null
  email?: string | null
  portalLinks?: Array<{ id?: string; label: string; url: string }> | null
  phdBadgeText?: string | null
  primaryCta?: { label?: string | null; url?: string | null }
  navigationMenu?: Array<{
    id?: string
    label: string
    url?: string | null
    subLinks?: Array<{ id?: string; label: string; url: string }> | null
  }> | null
}

export interface FooterGlobal {
  aboutText?: string | null
  address?: string | null
  helplineNumber?: string | null
  email?: string | null
  antiRaggingNumber?: string | null
  emergencyNumber?: string | null
  quickLinks?: Array<{ id?: string; label: string; url: string }> | null
  academicLinks?: Array<{ id?: string; label: string; url: string }> | null
  socialLinks?: Array<{ id?: string; platform: string; url: string }> | null
  copyrightText?: string | null
  bottomLinks?: Array<{ id?: string; label: string; url: string }> | null
}

export interface SiteSettingsGlobal {
  universityName?: string | null
  universityShortName?: string | null
  establishedYear?: string | null
  logo?: Media | string | null
  favicon?: Media | string | null
  announcementBanner?: {
    enabled?: boolean | null
    text?: string | null
    link?: string | null
    variant?: 'amber' | 'navy' | 'green' | 'red' | null
  } | null
}
